apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - 
          name: postgres
          emptyDir: {}
      containers:
        - 
          env:
            - 
              name: POSTGRES_USER
              value: postgres
            - 
              name: POSTGRES_PASSWORD
              value: postgres
          image: postgres:9.4
          name: postgres
          ports:
            - 
              containerPort: 5432
          volumeMounts:
            - 
              mountPath: /var/lib/mysql
              name: mysql-vol
            - 
              mountPath: /docker-entrypoint-initdb.d
              name: mysql-init-vol
