apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - 
          name: postgres
          emptyDir: {}
      containers:
        - 
          env:
            - 
              name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: postgres
            - 
              name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres
          image: postgres:9.4
          name: postgres
          ports:
            - 
              containerPort: 5432
          volumeMounts:
            - 
              mountPath: /var/lib/postgresql/data
              name: postgres
